{% set name = "aioredis" %}
{% set version = "1.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 86da2748fb0652625a8346f413167f078ec72bdc76e217db7e605a059cd56e86

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - async-timeout
    - hiredis
    - pip
    - python >3.5
  run:
    - async-timeout
    - hiredis
    - python >3.5

test:
  imports:
    - aioredis
    - aioredis.commands
    - aioredis.sentinel

about:
  home: https://github.com/aio-libs/aioredis
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: asyncio (PEP 3156) Redis support
  doc_url: http://aioredis.readthedocs.io/

extra:
  recipe-maintainers:
    - epruesse
