{% set name = "aioredis" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a2de4b614e6a5f8e104238924294dc4e811aefbe17ddf52c04a93cbf06e67db

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - async-timeout
    - typing-extensions
    - python >=3.6

test:
  imports:
    - aioredis
    - aioredis.commands
    - aioredis.sentinel
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/aio-libs/aioredis
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: asyncio (PEP 3156) Redis support
  doc_url: http://aioredis.readthedocs.io/

extra:
  recipe-maintainers:
    - epruesse
    - synapticarbors
